#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/newLineList.sh"

spotifyApiCmdDir="$1"

devicesJson="$("$spotifyApiCmdDir/getDevices")" || exit 1

allDevices=""
while read -r device; do
	name="$(echo "$device" | jq -r ".name")"
	id="$(echo "$device" | jq -r '.id')"

	deviceNewLineList="$(newLineList "$name" "$id")"
	allDevices+="${deviceNewLineList}"$'\n'
done < <(echo "$devicesJson" | jq -c '.devices[]')

printf "%s" "$allDevices"
