#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/newLineList.sh"

spotifyApiCmdDir="$3"
limit="$2"
playlistId="$1"

playlistJson="$("$spotifyApiCmdDir/getPlaylistTracks" "$playlistId" "$limit")" || exit 1

function handleTrack() {
	name="$(echo "$1" | jq -r '.track.name')"
	artist="$(echo "$1" | jq -r '.track.artists[0].name')"
	uri="$(echo "$1" | jq -r '.track.uri')"
}

function handleEpisode() {
	name="$(echo "$1" | jq -r '.track.name')"
	artist=""
	uri="$(echo "$1" | jq -r '.track.uri')"
}

allTracks="$(echo "$playlistJson" | jq -r '.next')"$'\n'
while read -r track; do
	typ="$(echo "$track" | jq -r '.track.type')"
	[ "$typ" = "track" ] && handleTrack "$track"
	[ "$typ" = "episode" ] && handleEpisode "$track"

	trackNewLineList="$(newLineList "$name" "$artist" "$uri")"
	allTracks+="${trackNewLineList}"$'\n'
done < <(echo "$playlistJson" | jq -c '.items[]')

printf "%s" "$allTracks"
